// <auto-generated />
namespace BITCollege_DP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class A4Complete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(A4Complete));
        
        string IMigrationMetadata.Id
        {
            get { return "202402281655292_A4Complete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
